try{
    console.log(x);
}
catch(err){
    throw new Error("Declare x first ");
}